ktor {
    deployment {
        port = 8080
        host = "0.0.0.0"
    }
    application {
        modules = [com.example.bakendorderwhatsapp.ApplicationKt.module]
    }
}

database {
    # Override with env vars when needed (Render internal host, etc.)
    url = "jdbc:postgresql://dpg-dak5qbid0e5s73b404e0-a.oregon-postgres.render.com:5432/orderwhatsapp"
    url = ${?DATABASE_URL}
    user = "orderwhatsapp_user"
    user = ${?DATABASE_USER}
    password = ${DATABASE_PASSWORD}
    driver = "org.postgresql.Driver"
    maxPoolSize = "10"
}
